name: "lastDockEx"
services:
  db:
    image: "postgres:alpine"
    restart: "always"
    shm_size: "128mb"
    environment:
      POSTGRES_USER: "bob"
      POSTGRES_PASSWORD: "${USER_PASS}"
      POSTGRES_DB: "lastdockex_db"
    volumes:
      - "db_data:/var/lib/postgresql/data"
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    networks:
      - "backend"

  back_write:
    build:
      context: "./back"
      dockerfile: "Dockerfile_write"
    restart: "always"
    shm_size: "256mb"
    networks:
      - "backend"
      - "middle"

  back_read:
    build:
      context: "./back"
      dockerfile: "Dockerfile_read"
    restart: "always"
    shm_size: "256mb"
    networks:
      - "backend"
      - "middle"

  front:
    build:
      context: "./front"
      dockerfile: "Dockerfile"
    restart: "always"
    shm_size: "256mb"
    ports:
      - "80:80"
    networks:
      - "middle"
      - "frontend"

networks:
  backend:
    internal: true
  middle:
    internal: true
  frontend:

volumes:
  db_data:
