name: "lastDockEx"
services:
  db:
    image: "postgres:alpine"
    restart: "always"
    shm_size: "128mb"
    environment:
      POSTGRES_USER: "bob"
      POSTGRES_PASSWORD: "${USER_PASS}"
      POSTGRES_DB: "lastdockex_db"
    volumes:
      - "db_data:/var/lib/postgresql/data"
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    ports:
      - "5432:5432"
    networks:
      - "backend"

  back:
    build:
      context: "./back"
      dockerfile: "Dockerfile"
    restart: "always"
    shm_size: "256mb"
    ports:
      - "1234:8080"
    networks:
      - "backend"
      - "middle"

networks:
  backend:
    # internal: true
  middle:
    # internal: true

volumes:
  db_data:
